"""
schemas/coach.py — Pydantic schemas for Coach agent data contracts.
"""
from datetime import datetime
from typing import Literal
from pydantic import BaseModel, Field
from app.schemas.rule_result import RuleResult


class CoachReadinessSchema(BaseModel):
    status: Literal["Learning", "Active"] = Field("Learning", description="Current operational state of Coach")
    ready: bool = Field(False, description="True if minimum history threshold is met")
    progress_percentage: float = Field(0.0, description="Percentage of required transactions recorded (0 to 100)")
    tx_count: int = Field(0, description="Total transactions collected")
    required_tx: int = Field(20, description="Minimum transactions needed for Active status")
    days_history: int = Field(0, description="Days of history available")
    required_days: int = Field(30, description="Minimum days of history needed for Active status")
    message: str = Field(..., description="Human readable readiness status message")


class CoachScoreSchema(BaseModel):
    score: int = Field(..., ge=0, le=100, description="Deterministic financial habit score (0-100)")
    rating: str = Field(..., description="Qualitative rating label (e.g. Excellent, Good, Needs Attention)")
    reasons: list[str] = Field(default_factory=list, description="Reasoning factors behind the score")


class CoachHabitsSchema(BaseModel):
    most_frequent_category: str | None = None
    largest_category: str | None = None
    avg_daily_spend: float = 0.0
    avg_weekly_spend: float = 0.0
    category_breakdown: list[dict] = Field(default_factory=list)


class CoachSummaryResponseSchema(BaseModel):
    status: Literal["Learning", "Active"] = "Learning"
    readiness: CoachReadinessSchema
    score: CoachScoreSchema | None = None
    habits: CoachHabitsSchema
    recommendations: list[RuleResult] = Field(default_factory=list)
    ai_coaching: str = Field(..., description="Natural language coaching text generated by LLM formatter")
    last_updated: datetime
    currency: str = "INR"
